<?php
// public_html/api/reports/export.php
require __DIR__ . '/../lib/cors.php';
require __DIR__ . '/../lib/json.php';
require __DIR__ . '/../lib/auth.php';
require __DIR__ . '/../db.php';

$user = require_auth();

$serviceName = $_GET['service'] ?? '';
$from        = $_GET['from'] ?? '';
$to          = $_GET['to'] ?? '';

$SERVICE_MAP = require __DIR__ . '/../lib/serviceMap.php';

if (!isset($SERVICE_MAP[$serviceName])) {
    http_response_code(400);
    header('Content-Type: text/plain');
    echo 'Unknown service';
    exit;
}

$table = $SERVICE_MAP[$serviceName]['table'];

// Build optional WHERE clause
$conditions = [];
$params     = [];

if ($from !== '' && preg_match('/^\d{4}-\d{2}-\d{2}$/', $from)) {
    $conditions[] = 'date >= ?';
    $params[]     = $from;
}
if ($to !== '' && preg_match('/^\d{4}-\d{2}-\d{2}$/', $to)) {
    $conditions[] = 'date <= ?';
    $params[]     = $to;
}

$where = $conditions ? 'WHERE ' . implode(' AND ', $conditions) : '';

try {
    $stmt = $pdo->prepare("SELECT * FROM `$table` $where ORDER BY date ASC");
    $stmt->execute($params);
    $rows = $stmt->fetchAll();
} catch (PDOException $e) {
    error_log('[export] ' . $e->getMessage());
    http_response_code(500);
    header('Content-Type: text/plain');
    echo 'Database error';
    exit;
}

// Build filename
$safeName = preg_replace('/[^A-Za-z0-9._-]+/', '_', $serviceName);
$suffix   = '';
if ($from !== '' || $to !== '') {
    $suffix = '-' . ($from ?: 'start') . '_to_' . ($to ?: 'end');
}
$filename = $safeName . $suffix . '.csv';

// Send CSV headers
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// UTF-8 BOM
echo "\xEF\xBB\xBF";

$out = fopen('php://output', 'w');

// ═══════════════════════════════════════════════════════════
// REPORT HEADER
// ═══════════════════════════════════════════════════════════

fputcsv($out, ['Foursquare Gospel Church, VGC']);
fputcsv($out, ['Attendance Report']);
fputcsv($out, []);   // blank line

fputcsv($out, ['Service:', $serviceName]);

// Period
if ($from !== '' && $to !== '') {
    fputcsv($out, ['Period:', $from . ' to ' . $to]);
} elseif ($from !== '') {
    fputcsv($out, ['Period:', 'From ' . $from]);
} elseif ($to !== '') {
    fputcsv($out, ['Period:', 'Up to ' . $to]);
} else {
    fputcsv($out, ['Period:', 'All time']);
}

fputcsv($out, ['Generated:', date('F j, Y \a\t g:i A')]);
fputcsv($out, ['Generated by:', $user['code'] ?? 'unknown']);
fputcsv($out, ['Total records:', count($rows)]);
fputcsv($out, []);   // blank line

// ═══════════════════════════════════════════════════════════
// DATA TABLE
// ═══════════════════════════════════════════════════════════

if (!empty($rows)) {
    // Header row
    fputcsv($out, array_keys($rows[0]));

    // Data rows
    foreach ($rows as $row) {
        fputcsv($out, $row);
    }
} else {
    fputcsv($out, ['No records found for this range.']);
}

// ═══════════════════════════════════════════════════════════
// SUMMARY (averages + totals)
// ═══════════════════════════════════════════════════════════

if (!empty($rows)) {
    $columns = array_keys($rows[0]);

    // Determine numeric columns (skip id, date, and metadata columns)
    $numericColumns = [];
    foreach ($columns as $col) {
        if (in_array($col, ['id', 'date', 'submitted_by', 'submitted_at', 'updated_by', 'updated_at'], true)) {
            continue;
        }
        if (isset($rows[0][$col]) && is_numeric($rows[0][$col])) {
            $numericColumns[] = $col;
        }
    }

    fputcsv($out, []);   // blank line
    fputcsv($out, ['Summary']);
    fputcsv($out, []);

    // Averages
    foreach ($numericColumns as $col) {
        $sum   = 0;
        $count = 0;
        foreach ($rows as $row) {
            if (isset($row[$col]) && is_numeric($row[$col])) {
                $sum += (float)$row[$col];
                $count++;
            }
        }
        $avg = $count > 0 ? $sum / $count : 0;
        fputcsv($out, ['Average ' . $col . ':', number_format($avg, 1)]);
    }

    fputcsv($out, []);

    // Totals
    foreach ($numericColumns as $col) {
        $sum = 0;
        foreach ($rows as $row) {
            if (isset($row[$col]) && is_numeric($row[$col])) {
                $sum += (float)$row[$col];
            }
        }
        fputcsv($out, ['Total ' . $col . ':', number_format($sum, 0)]);
    }
}

// ═══════════════════════════════════════════════════════════
// FOOTER
// ═══════════════════════════════════════════════════════════

fputcsv($out, []);
fputcsv($out, ['— End of Report —']);

fclose($out);